apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: microservice-blogs
build:
  artifacts:
  - image: shockwater/blog-client
    context: comments
  - image: shockwater/blog-comments
    context: client
  - image: shockwater/blog-event-bus
    context: event-bus
  - image: shockwater/blog-moderation
    context: moderation
  - image: shockwater/blog-posts
    context: posts
  - image: shockwater/blog-query
    context: query
deploy:
  kubectl:
    manifests:
    - infra/k8s/client-deployment.yaml
    - infra/k8s/comments-deployment.yaml
    - infra/k8s/event-bus-deployment.yaml
    - infra/k8s/ingress-service.yaml
    - infra/k8s/moderation-deployment.yaml
    - infra/k8s/posts-deployment.yaml
    - infra/k8s/posts-service.yaml
    - infra/k8s/query-deployment.yaml
